<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" class="scroll-smooth">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $business['name'] }} — {{ __('site.meta_title') }}</title>
    <meta name="description" content="{{ __('site.meta_description') }}">
    <meta name="keywords" content="lavandería industrial Málaga, apartamentos turísticos, hoteles, hostelería, ropa de cama, toallas, recogida y entrega">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <link rel="canonical" href="{{ request()->url() }}">
    @foreach(['es', 'en', 'pt'] as $language)<link rel="alternate" hreflang="{{ $language }}" href="{{ url($language) }}">@endforeach
    <link rel="alternate" hreflang="x-default" href="{{ url('es') }}">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="es_ES">
    <meta property="og:url" content="{{ request()->url() }}">
    <meta property="og:site_name" content="{{ $business['name'] }}">
    <meta property="og:title" content="{{ $business['name'] }} — {{ __('site.meta_title') }}">
    <meta property="og:description" content="{{ __('site.meta_description') }}">
    <meta property="og:image" content="{{ asset('images/logo-cleaning-solution.png') }}">
    <meta name="twitter:card" content="summary_large_image">
    @php($localBusiness = [
        '@context' => 'https://schema.org',
        '@type' => 'DryCleaningOrLaundry',
        '@id' => url('/').'#business',
        'name' => $business['name'],
        'description' => __('site.meta_description'),
        'url' => url('/'),
        'image' => asset('images/logo-cleaning-solution.png'),
        'telephone' => $business['phone'],
        'email' => $business['email'],
        'priceRange' => '€€',
        'areaServed' => ['@type' => 'City', 'name' => 'Málaga'],
        'address' => ['@type' => 'PostalAddress', 'addressLocality' => 'Málaga', 'addressRegion' => 'Andalucía', 'addressCountry' => 'ES'],
        'contactPoint' => ['@type' => 'ContactPoint', 'telephone' => $business['phone'], 'contactType' => 'customer service', 'availableLanguage' => 'Spanish'],
    ])
    <script type="application/ld+json">{!! json_encode($localBusiness, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
    @if (file_exists(public_path('build/manifest.json')))
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @else
        <script src="https://cdn.tailwindcss.com"></script>
        <style>body{font-family:Instrument Sans,ui-sans-serif,system-ui,sans-serif}.font-display{font-family:Georgia,'Times New Roman',serif}</style>
    @endif
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body class="overflow-x-hidden font-sans text-slate-700 antialiased" x-data="{ open:false, activeFaq:null, modal:null, scrolled:false }" @scroll.window="scrolled = window.scrollY > 20">
<header class="fixed inset-x-0 top-0 z-50 transition-all duration-300" :class="scrolled ? 'bg-white/90 py-3 shadow-sm backdrop-blur-xl' : 'bg-transparent py-5'">
 <nav class="mx-auto flex max-w-7xl items-center justify-between px-5 lg:px-8" aria-label="Navegación principal">
  <a href="#inicio" class="shrink-0" aria-label="{{ $business['name'] }} — Inicio"><img src="{{ asset('images/logo-cleaning-solution.png') }}" alt="Logo de {{ $business['name'] }}" class="h-14 w-14 rounded-xl object-cover shadow-sm sm:h-16 sm:w-16"></a>
  <div class="hidden items-center gap-6 text-sm font-semibold text-slate-600 lg:flex"><a href="#servicios">{{ __('site.nav.services') }}</a><a href="#nosotros">{{ __('site.nav.lodgings') }}</a><a href="#proceso">{{ __('site.nav.process') }}</a><a href="#experiencias">{{ __('site.nav.operations') }}</a><a href="#precios">{{ __('site.nav.quote') }}</a><a href="#preguntas">FAQ</a></div>
  <div class="hidden items-center gap-3 sm:flex"><div class="flex rounded-full border border-sky-100 bg-white p-1 text-xs font-bold">@foreach(['es' => 'ES', 'en' => 'EN', 'pt' => 'PT'] as $code => $label)<a href="{{ url($code) }}" lang="{{ $code }}" class="rounded-full px-2.5 py-1.5 {{ app()->getLocale() === $code ? 'bg-sky-900 text-white' : 'text-sky-800 hover:bg-sky-50' }}">{{ $label }}</a>@endforeach</div><a href="https://wa.me/{{ $business['whatsapp'] }}" class="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-500 text-white shadow-sm transition hover:scale-105 hover:bg-emerald-600" aria-label="WhatsApp"><x-app-icon name="whatsapp" class="h-6 w-6"/></a><x-button href="https://wa.me/{{ $business['whatsapp'] }}" class="px-4 py-2.5">{{ __('site.nav.pickup') }}</x-button></div>
  <button @click="open=!open" class="rounded-xl p-2 text-slate-800 lg:hidden" aria-label="Abrir menú"><span class="block h-0.5 w-6 bg-current mb-1.5"></span><span class="block h-0.5 w-6 bg-current"></span></button>
 </nav>
 <div x-show="open" x-transition class="mx-4 mt-3 rounded-2xl bg-white p-5 shadow-xl lg:hidden" @click.outside="open=false"><div class="grid gap-4 text-sm font-semibold"><div class="flex gap-2">@foreach(['es' => 'ES', 'en' => 'EN', 'pt' => 'PT'] as $code => $label)<a href="{{ url($code) }}" class="rounded-full px-3 py-2 {{ app()->getLocale() === $code ? 'bg-sky-900 text-white' : 'bg-sky-50 text-sky-800' }}">{{ $label }}</a>@endforeach</div><a @click="open=false" href="#servicios">{{ __('site.nav.services') }}</a><a @click="open=false" href="#nosotros">{{ __('site.nav.lodgings') }}</a><a @click="open=false" href="#proceso">{{ __('site.nav.process') }}</a><a @click="open=false" href="#precios">{{ __('site.nav.quote') }}</a><x-button href="https://wa.me/{{ $business['whatsapp'] }}">WhatsApp</x-button></div></div>
</header>

<main>
 <section id="inicio" class="relative isolate overflow-hidden pt-32 sm:pt-40"><div class="absolute -top-40 right-[-12rem] -z-10 h-[35rem] w-[35rem] rounded-full bg-sky-100 blur-3xl"></div><div class="mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28">
   <div><p class="mb-6 inline-flex items-center gap-2 rounded-full bg-sky-50 px-4 py-2 text-xs font-bold uppercase tracking-widest text-sky-700"><span class="h-2 w-2 rounded-full bg-sky-500"></span>{{ __('site.hero.eyebrow') }}</p><h1 class="font-display max-w-xl text-5xl font-semibold leading-[.98] tracking-[-.065em] text-slate-950 sm:text-6xl lg:text-7xl">{{ __('site.hero.title') }} <em class="font-normal text-sky-500">{{ __('site.hero.accent') }}</em></h1><p class="mt-7 max-w-lg text-lg leading-8 text-slate-500">{{ __('site.hero.text') }}</p><div class="mt-9 flex flex-wrap gap-3"><x-button href="https://wa.me/{{ $business['whatsapp'] }}">{{ __('site.nav.pickup') }}</x-button><x-button href="#servicios" variant="secondary">{{ __('site.hero.solutions') }}</x-button></div><div class="mt-10 flex flex-wrap items-center gap-x-7 gap-y-3 text-sm"><div><b class="text-slate-800">{{ __('site.hero.week') }}</b> <span class="text-slate-500">{{ __('site.hero.week_label') }}</span></div><span class="h-8 w-px bg-slate-200"></span><div class="flex flex-wrap gap-4"><span class="inline-flex items-center gap-1.5"><x-app-icon name="check" class="h-4 w-4 text-sky-500"/>{{ __('site.hero.pickup') }}</span><span class="inline-flex items-center gap-1.5"><x-app-icon name="check" class="h-4 w-4 text-sky-500"/>{{ __('site.hero.delivery') }}</span></div></div></div>
   <div class="relative mx-auto w-full max-w-xl"><div class="absolute -inset-5 rounded-[3rem] bg-sky-100/80 -rotate-6"></div><img class="relative aspect-[4/4.5] w-full rounded-[2.5rem] object-cover shadow-2xl shadow-sky-950/15" src="https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=1000&q=85" alt="Prendas limpias y cuidadosamente dobladas"><div class="absolute right-5 top-5 overflow-hidden rounded-2xl shadow-2xl ring-1 ring-white/30 sm:right-7 sm:top-7"><img src="{{ asset('images/logo-cleaning-solution.png') }}" alt="" class="h-24 w-24 object-cover sm:h-32 sm:w-32"></div><div class="absolute -bottom-6 -left-3 rounded-2xl bg-white p-4 shadow-xl sm:-left-8"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-50 text-sky-600"><x-app-icon name="check" class="h-5 w-5"/></span><div><b class="block text-sm text-slate-900">Prendas listas</b><span class="text-xs text-slate-500">Cuidado que se nota</span></div></div></div></div>
 </div></section>
 <section class="border-y border-sky-100 bg-sky-50/60"><div class="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-sky-100 px-5 sm:grid-cols-4 lg:px-8">@foreach(__('site.stats') as [$num,$label])<div class="py-7 text-center"><strong class="block text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{{ $num }}</strong><span class="mt-1 block text-xs font-medium text-slate-500">{{ $label }}</span></div>@endforeach</div></section>
 <section id="nosotros" class="mx-auto grid max-w-7xl items-center gap-14 px-5 py-24 lg:grid-cols-2 lg:px-8"><div class="relative"><img class="aspect-square rounded-[2rem] object-cover" loading="lazy" src="https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=900&q=80" alt="{{ __('site.about.eyebrow') }}"><div class="absolute bottom-6 right-6 max-w-48 rounded-2xl bg-slate-950 p-5 text-white"><span class="text-3xl font-bold text-sky-300">7 / 7</span><p class="mt-1 text-sm leading-5 text-slate-300">{{ __('site.about.badge') }}</p></div></div><div><x-section-heading :eyebrow="__('site.about.eyebrow')" :title="__('site.about.title')" :text="__('site.about.text')"/><div class="mt-9 grid gap-5 sm:grid-cols-3">@foreach(__('site.about.items') as [$t,$d])<div><h3 class="font-bold text-slate-900">{{ $t }}</h3><p class="mt-1 text-sm leading-5 text-slate-500">{{ $d }}</p></div>@endforeach</div><x-button href="https://wa.me/{{ $business['whatsapp'] }}" variant="secondary" class="mt-9">{{ __('site.about.whatsapp') }}</x-button></div></section>
 <section id="servicios" class="bg-slate-50 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center :eyebrow="__('site.services.eyebrow')" :title="__('site.services.title')" :text="__('site.services.text')"/><div class="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach(__('site.services.items') as [$icon,$title,$description])<x-service-card :icon="$icon" :title="$title" :description="$description" />@endforeach</div></div></section>
 <section class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="grid overflow-hidden rounded-[2.5rem] bg-slate-950 lg:grid-cols-2"><img class="h-full min-h-80 w-full object-cover" loading="lazy" src="https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=900&q=80" alt="Cuidado de prendas en lavandería"><div class="p-9 text-white sm:p-14"><p class="text-xs font-bold uppercase tracking-[.2em] text-sky-300">El servicio más elegido</p><h2 class="mt-5 font-display text-4xl font-semibold tracking-tight">Lavado + Secado</h2><p class="mt-5 max-w-md leading-7 text-slate-300">El equilibrio ideal entre practicidad y cuidado. Recibí tus prendas perfectamente limpias, secas y dobladas.</p><ul class="mt-8 space-y-3 text-sm">@foreach(['Lavado profesional por categoría','Secado con temperatura controlada','Doblado cuidado, listo para guardar'] as $point)<li class="flex gap-3"><x-app-icon name="check" class="h-5 w-5 text-sky-300"/>{{ $point }}</li>@endforeach</ul><x-button href="#contacto" class="mt-9 bg-sky-400 text-slate-950 hover:bg-sky-300">Solicitar servicio</x-button></div></div></section>
 <section id="proceso" class="border-y border-slate-100 bg-white py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center :eyebrow="__('site.process.eyebrow')" :title="__('site.process.title')"/><div class="relative mt-16 grid gap-10 md:grid-cols-4"><div class="absolute left-[12%] right-[12%] top-7 hidden h-px bg-sky-100 md:block"></div>@foreach(__('site.process.items') as [$n,$t,$d])<div class="relative text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-sky-500 text-sm font-bold text-white ring-8 ring-white">{{ $n }}</span><h3 class="mt-6 font-bold text-slate-900">{{ $t }}</h3><p class="mx-auto mt-2 max-w-48 text-sm leading-6 text-slate-500">{{ $d }}</p></div>@endforeach</div></div></section>
 <section id="experiencias" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><x-section-heading :eyebrow="__('site.operations.eyebrow')" :title="__('site.operations.title')"/><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">@foreach(__('site.operations.items') as [$title,$copy])<article class="rounded-3xl bg-sky-50 p-7"><x-app-icon name="sparkles" class="h-7 w-7 text-sky-500"/><h3 class="mt-12 text-lg font-bold text-slate-900">{{ $title }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $copy }}</p></article>@endforeach</div></section>
 <section class="bg-slate-950 py-24 text-white"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center eyebrow="Nuestro compromiso" title="Un servicio pensado para no detener tu operativa" text="Sabemos que cada cambio de huésped cuenta. Por eso trabajamos con tres prioridades claras." class="[&>h2]:text-white [&>p]:text-slate-300"/><div class="mt-14 grid gap-5 md:grid-cols-3">@foreach([['Puntualidad','Coordinamos rutas de recogida y entrega para que dispongas de los textiles cuando los necesitas.'],['Presentación impecable','Ropa de cama, baño y servicio limpia, fresca, doblada y preparada para su reposición.'],['Comunicación directa','Atención ágil por WhatsApp para organizar volúmenes, horarios y necesidades especiales.']] as [$title,$copy])<article class="rounded-3xl bg-white/5 p-7 ring-1 ring-white/10"><x-app-icon name="check" class="h-7 w-7 text-sky-300"/><h3 class="mt-6 text-xl font-bold">{{ $title }}</h3><p class="mt-3 leading-7 text-slate-300">{{ $copy }}</p></article>@endforeach</div><div class="mt-14 border-t border-white/10 pt-10"><p class="text-center text-xs font-bold uppercase tracking-[.25em] text-slate-400">Especialistas en textiles para</p><div class="mt-8 flex flex-wrap justify-center gap-x-12 gap-y-5 text-lg font-bold tracking-widest text-slate-300"><span>APARTAMENTOS</span><span>HOTELES</span><span>HOSTALES</span><span>RESTAURACIÓN</span></div></div></div></section>
 <section class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><x-section-heading center eyebrow="Nuestro espacio" title="Cuidado en cada etapa"/><div class="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">@foreach(['photo-1558618666-fcd25c85cd64','photo-1582735689369-4fe89db7114c','photo-1604335399105-a0c585fd81a1','photo-1626806787461-102c1bfaaea1'] as $i=>$photo)<button @click="modal={{ $i }}" class="group overflow-hidden rounded-2xl {{ $i === 0 ? 'row-span-2' : '' }}"><img class="h-full min-h-40 w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" src="https://images.unsplash.com/{{ $photo }}?auto=format&fit=crop&w=700&q=80" alt="Instalaciones y proceso de {{ $business['name'] }}"></button>@endforeach</div></section>
 <section id="precios" class="bg-sky-50 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center eyebrow="Presupuesto profesional" title="Una propuesta adaptada a tu alojamiento" text="La tarifa se calcula según el volumen, la frecuencia y los tipos de textiles. Escríbenos y te enviaremos una propuesta clara para tu operativa."/><div class="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Apartamentos turísticos','Hoteles y hostales','Restauración','Servicio recurrente'] as $item)<div class="rounded-2xl bg-white p-6 text-center shadow-sm"><p class="font-bold text-slate-900">{{ $item }}</p><p class="mt-4 text-lg font-bold text-sky-600">Presupuesto a medida</p><p class="mt-1 text-xs text-slate-400">Según volumen y frecuencia</p></div>@endforeach</div><div class="mt-10 text-center"><x-button href="https://wa.me/{{ $business['whatsapp'] }}?text=Hola%2C%20quiero%20solicitar%20un%20presupuesto%20para%20mi%20alojamiento%20en%20M%C3%A1laga.">Solicitar presupuesto</x-button></div></div></section>
 <section id="preguntas" class="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><x-section-heading eyebrow="Te ayudamos" title="Preguntas frecuentes" text="Todo lo que necesitás saber, antes de dejarnos el trabajo."/><div class="divide-y divide-slate-200">@foreach([['¿Cuánto demora el servicio?','El tiempo depende del servicio y volumen. Al confirmar tu solicitud te indicamos una fecha de entrega clara.'],['¿Lavan todo tipo de prendas?','Evaluamos la etiqueta y composición de cada prenda para aplicar el tratamiento adecuado.'],['¿Realizan lavado en seco?','Sí, contamos con cuidado especializado para prendas delicadas que requieren este proceso.'],['¿Puedo solicitar retiro y entrega?','Consultanos la disponibilidad para tu zona y coordinaremos la opción más cómoda para ti.'],['¿Cómo puedo pagar?','Te informaremos las opciones de pago disponibles al coordinar tu servicio.']] as $index=>[$q,$a])<div class="py-5"><button @click="activeFaq === {{ $index }} ? activeFaq=null : activeFaq={{ $index }}" class="flex w-full items-center justify-between gap-5 text-left font-bold text-slate-900"><span>{{ $q }}</span><span class="text-xl text-sky-500" x-text="activeFaq === {{ $index }} ? '−' : '+'"></span></button><p x-show="activeFaq === {{ $index }}" x-collapse class="pt-3 pr-8 leading-7 text-slate-500">{{ $a }}</p></div>@endforeach</div></section>
 <section id="contacto" class="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div class="grid overflow-hidden rounded-[2.5rem] bg-sky-500 lg:grid-cols-2"><div class="p-9 text-white sm:p-14"><p class="text-xs font-bold uppercase tracking-[.2em] text-sky-100">{{ __('site.contact.eyebrow') }}</p><h2 class="mt-5 font-display text-4xl font-semibold tracking-tight">{{ __('site.contact.title') }}</h2><p class="mt-5 leading-7 text-sky-50">{{ __('site.contact.text') }}</p><div class="mt-10 space-y-5 text-sm"><div class="flex gap-3"><x-app-icon name="pin" class="h-5 w-5 text-sky-100"/><span>Málaga</span></div><div class="flex gap-3"><x-app-icon name="clock" class="h-5 w-5 text-sky-100"/><span>7 / 7</span></div><div class="flex gap-3"><x-app-icon name="check" class="h-5 w-5 text-sky-100"/><span>{{ __('site.hero.delivery') }}</span></div></div></div><div class="flex flex-col items-center justify-center bg-white p-9 text-center sm:p-14"><span class="flex h-20 w-20 items-center justify-center rounded-full bg-emerald-500 text-white shadow-xl shadow-emerald-600/20"><x-app-icon name="whatsapp" class="h-10 w-10"/></span><h3 class="mt-7 text-2xl font-bold tracking-tight text-sky-950">{{ __('site.contact.cta_title') }}</h3><p class="mt-3 max-w-sm leading-7 text-slate-500">{{ __('site.contact.cta_text') }}</p><a href="https://wa.me/{{ $business['whatsapp'] }}" class="mt-8 inline-flex items-center justify-center gap-3 rounded-full bg-emerald-500 px-7 py-4 text-sm font-bold text-white shadow-lg shadow-emerald-600/20 transition hover:-translate-y-0.5 hover:bg-emerald-600"><x-app-icon name="whatsapp" class="h-5 w-5"/>{{ __('site.contact.button') }}</a><p class="mt-4 text-xs text-slate-400">{{ __('site.contact.response') }}</p></div></div></section>
</main>
<footer class="bg-slate-950 text-slate-400"><div class="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><a href="#inicio" aria-label="{{ $business['name'] }} — Inicio"><img src="{{ asset('images/logo-cleaning-solution.png') }}" alt="Logo de {{ $business['name'] }}" class="h-28 w-28 rounded-2xl object-cover"></a><p class="mt-4 max-w-52 text-sm leading-6">{{ $business['tagline'] }}</p></div><div><h3 class="font-bold text-white">Servicios</h3><ul class="mt-4 space-y-2 text-sm"><li>Ropa de cama</li><li>Toallas y baño</li><li>Textiles de hostelería</li><li>Recogida y entrega</li></ul></div><div><h3 class="font-bold text-white">Para empresas</h3><ul class="mt-4 space-y-2 text-sm"><li>Apartamentos turísticos</li><li>Hoteles y hostales</li><li>Restauración</li><li>Málaga capital</li></ul></div><div><h3 class="font-bold text-white">Contacto</h3><a href="https://wa.me/{{ $business['whatsapp'] }}" class="mt-4 inline-flex h-12 w-12 items-center justify-center rounded-full bg-emerald-500 text-white transition hover:bg-emerald-600" aria-label="Contactar por WhatsApp"><x-app-icon name="whatsapp" class="h-6 w-6"/></a><p class="mt-4 text-sm">Todos los días<br>Recogida y entrega en el día</p></div></div><div class="border-t border-white/10 px-5 py-6 text-center text-xs">© 2026 {{ $business['name'] }}. Todos los derechos reservados.</div></footer>
<a href="https://wa.me/{{ $business['whatsapp'] }}?text=Hola%2C%20quiero%20informaci%C3%B3n%20sobre%20el%20servicio%20de%20lavander%C3%ADa%20para%20mi%20alojamiento%20en%20M%C3%A1laga." class="fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500 text-white shadow-xl shadow-emerald-600/30 transition hover:scale-110" aria-label="Contactar por WhatsApp"><x-app-icon name="whatsapp" class="h-7 w-7"/></a>
<div x-show="modal !== null" x-transition class="fixed inset-0 z-[60] grid place-items-center bg-slate-950/90 p-5" @keydown.escape.window="modal=null"><button @click="modal=null" class="absolute right-7 top-6 text-3xl text-white" aria-label="Cerrar">×</button><img :src="['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1500&q=90','https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=1500&q=90','https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=1500&q=90','https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=1500&q=90'][modal]" class="max-h-[85vh] max-w-full rounded-2xl object-contain" alt="Galería ampliada"></div>
</body></html>
