<!DOCTYPE html>
<html lang="es" class="scroll-smooth">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $business['name'] }} — Lavandería profesional en Asunción</title>
    <meta name="description" content="Lavandería profesional: cuidamos tus prendas para que disfrutes de más tiempo para ti.">
    <meta name="keywords" content="lavandería, lavado, secado, planchado, Asunción">
    <meta property="og:title" content="{{ $business['name'] }} — Ropa impecable, tiempo para ti"><meta property="og:description" content="Cuidado profesional para cada prenda.">
    <script type="application/ld+json">{"@@context":"https://schema.org","@type":"DryCleaningOrLaundry","name":"{{ $business['name'] }}","telephone":"{{ $business['phone'] }}","email":"{{ $business['email'] }}","address":{"@type":"PostalAddress","streetAddress":"{{ $business['address'] }}"}}</script>
    @if (file_exists(public_path('build/manifest.json')))
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @else
        <script src="https://cdn.tailwindcss.com"></script>
        <style>body{font-family:Instrument Sans,ui-sans-serif,system-ui,sans-serif}.font-display{font-family:Georgia,'Times New Roman',serif}</style>
    @endif
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body class="overflow-x-hidden bg-[#fcfeff] font-sans text-slate-700 antialiased" x-data="{ open:false, activeFaq:null, modal:null, scrolled:false }" @scroll.window="scrolled = window.scrollY > 20">
<header class="fixed inset-x-0 top-0 z-50 transition-all duration-300" :class="scrolled ? 'bg-white/90 py-3 shadow-sm backdrop-blur-xl' : 'bg-transparent py-5'">
 <nav class="mx-auto flex max-w-7xl items-center justify-between px-5 lg:px-8" aria-label="Navegación principal">
  <a href="#inicio" class="flex items-center gap-2 text-xl font-bold tracking-tight text-slate-950"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-500 text-white"><x-icon name="sparkles" class="h-5 w-5"/></span>{{ $business['name'] }}<i class="text-sky-500">.</i></a>
  <div class="hidden items-center gap-6 text-sm font-semibold text-slate-600 lg:flex"><a href="#servicios">Servicios</a><a href="#nosotros">Nosotros</a><a href="#proceso">Cómo funciona</a><a href="#experiencias">Experiencias</a><a href="#precios">Precios</a><a href="#preguntas">FAQ</a></div>
  <div class="hidden items-center gap-3 sm:flex"><a href="https://wa.me/{{ $business['whatsapp'] }}" class="text-sm font-bold text-sky-600">WhatsApp</a><x-button href="#contacto" class="px-4 py-2.5">Solicitar servicio</x-button></div>
  <button @click="open=!open" class="rounded-xl p-2 text-slate-800 lg:hidden" aria-label="Abrir menú"><span class="block h-0.5 w-6 bg-current mb-1.5"></span><span class="block h-0.5 w-6 bg-current"></span></button>
 </nav>
 <div x-show="open" x-transition class="mx-4 mt-3 rounded-2xl bg-white p-5 shadow-xl lg:hidden" @click.outside="open=false"><div class="grid gap-4 text-sm font-semibold"><a @click="open=false" href="#servicios">Servicios</a><a @click="open=false" href="#nosotros">Nosotros</a><a @click="open=false" href="#proceso">Cómo funciona</a><a @click="open=false" href="#precios">Precios</a><x-button href="#contacto">Solicitar servicio</x-button></div></div>
</header>

<main>
 <section id="inicio" class="relative isolate overflow-hidden pt-32 sm:pt-40"><div class="absolute -top-40 right-[-12rem] -z-10 h-[35rem] w-[35rem] rounded-full bg-sky-100 blur-3xl"></div><div class="mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28">
   <div><p class="mb-6 inline-flex items-center gap-2 rounded-full bg-sky-50 px-4 py-2 text-xs font-bold uppercase tracking-widest text-sky-700"><span class="h-2 w-2 rounded-full bg-sky-500"></span> Lavandería premium en Asunción</p><h1 class="font-display max-w-xl text-5xl font-semibold leading-[.98] tracking-[-.065em] text-slate-950 sm:text-6xl lg:text-7xl">Ropa limpia, fresca y <em class="font-normal text-sky-500">lista para disfrutar.</em></h1><p class="mt-7 max-w-lg text-lg leading-8 text-slate-500">Cuidamos tus prendas como si fueran nuestras, para que tengas más tiempo para lo que realmente importa.</p><div class="mt-9 flex flex-wrap gap-3"><x-button href="#contacto">Solicitar servicio</x-button><x-button href="#servicios" variant="secondary">Ver nuestros servicios</x-button></div><div class="mt-10 flex flex-wrap items-center gap-x-7 gap-y-3 text-sm"><div><div class="tracking-[.12em] text-amber-400">★★★★★</div><b class="text-slate-800">4.9/5</b> <span class="text-slate-500">clientes felices</span></div><span class="h-8 w-px bg-slate-200"></span><div class="flex gap-4"><span class="inline-flex items-center gap-1.5"><x-icon name="check" class="h-4 w-4 text-sky-500"/>Profesional</span><span class="inline-flex items-center gap-1.5"><x-icon name="check" class="h-4 w-4 text-sky-500"/>Rápido</span></div></div></div>
   <div class="relative mx-auto w-full max-w-xl"><div class="absolute -inset-5 rounded-[3rem] bg-sky-100/80 -rotate-6"></div><img class="relative aspect-[4/4.5] w-full rounded-[2.5rem] object-cover shadow-2xl shadow-sky-950/15" src="https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=1000&q=85" alt="Prendas limpias y cuidadosamente dobladas"><div class="absolute -bottom-6 -left-3 rounded-2xl bg-white p-4 shadow-xl sm:-left-8"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-500"><x-icon name="check" class="h-5 w-5"/></span><div><b class="block text-sm text-slate-900">Prendas listas</b><span class="text-xs text-slate-500">Cuidado que se nota</span></div></div></div></div>
 </div></section>
 <section class="border-y border-sky-100 bg-sky-50/60"><div class="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-sky-100 px-5 sm:grid-cols-4 lg:px-8">@foreach([['+1.000','Clientes satisfechos'],['+5 años','De experiencia'],['+50.000','Prendas cuidadas'],['4.9 / 5','Valoración media']] as [$num,$label])<div class="py-7 text-center"><strong class="block text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{{ $num }}</strong><span class="mt-1 block text-xs font-medium text-slate-500">{{ $label }}</span></div>@endforeach</div></section>
 <section id="nosotros" class="mx-auto grid max-w-7xl items-center gap-14 px-5 py-24 lg:grid-cols-2 lg:px-8"><div class="relative"><img class="aspect-square rounded-[2rem] object-cover" loading="lazy" src="https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=900&q=80" alt="Equipo preparando prendas"><div class="absolute bottom-6 right-6 max-w-44 rounded-2xl bg-slate-950 p-5 text-white"><span class="text-3xl font-bold text-sky-300">05</span><p class="mt-1 text-sm leading-5 text-slate-300">años elevando el cuidado de tu ropa.</p></div></div><div><x-section-heading eyebrow="Nuestra esencia" title="Más que lavar ropa, cuidamos lo importante para ti." text="Un servicio cercano y minucioso, creado para que recibas cada prenda impecable y con la tranquilidad de haberla dejado en las mejores manos."/><div class="mt-9 grid gap-5 sm:grid-cols-3">@foreach([['Calidad','Cuidamos cada detalle.'],['Confianza','Tu ropa está segura.'],['Compromiso','Cumplimos lo que prometemos.']] as [$t,$d])<div><h3 class="font-bold text-slate-900">{{ $t }}</h3><p class="mt-1 text-sm leading-5 text-slate-500">{{ $d }}</p></div>@endforeach</div><x-button href="#contacto" variant="secondary" class="mt-9">Conoce nuestra historia</x-button></div></section>
 <section id="servicios" class="bg-slate-50 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center eyebrow="Nuestros servicios" title="Todo lo que tu ropa necesita" text="Tratamos cada tipo de prenda con el proceso, el tiempo y los productos que merece."/><div class="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach([['shirt','Lavado profesional','Limpieza profunda y delicada para tus prendas de todos los días.'],['sparkles','Secado y doblado','Suavidad y orden para que solo tengas que guardar.'],['bag','Planchado impecable','Prendas listas para vestir, con acabados profesionales.'],['heart','Lavado en seco','Cuidado especializado para tus prendas más delicadas.'],['sparkles','Ropa de cama','Sábanas, acolchados y textiles que abrazan tu descanso.'],['clock','Servicio empresarial','Soluciones confiables para hoteles, oficinas y comercios.']] as [$icon,$title,$description])<x-service-card :icon="$icon" :title="$title" :description="$description" />@endforeach</div></div></section>
 <section class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="grid overflow-hidden rounded-[2.5rem] bg-slate-950 lg:grid-cols-2"><img class="h-full min-h-80 w-full object-cover" loading="lazy" src="https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=900&q=80" alt="Cuidado de prendas en lavandería"><div class="p-9 text-white sm:p-14"><p class="text-xs font-bold uppercase tracking-[.2em] text-sky-300">El servicio más elegido</p><h2 class="mt-5 font-display text-4xl font-semibold tracking-tight">Lavado + Secado</h2><p class="mt-5 max-w-md leading-7 text-slate-300">El equilibrio ideal entre practicidad y cuidado. Recibí tus prendas perfectamente limpias, secas y dobladas.</p><ul class="mt-8 space-y-3 text-sm">@foreach(['Lavado profesional por categoría','Secado con temperatura controlada','Doblado cuidado, listo para guardar'] as $point)<li class="flex gap-3"><x-icon name="check" class="h-5 w-5 text-sky-300"/>{{ $point }}</li>@endforeach</ul><x-button href="#contacto" class="mt-9 bg-sky-400 text-slate-950 hover:bg-sky-300">Solicitar servicio</x-button></div></div></section>
 <section id="proceso" class="border-y border-slate-100 bg-white py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center eyebrow="Simple y transparente" title="Así de fácil es tener tu ropa lista"/><div class="relative mt-16 grid gap-10 md:grid-cols-4"><div class="absolute left-[12%] right-[12%] top-7 hidden h-px bg-sky-100 md:block"></div>@foreach([['01','Solicita tu servicio','Elige lo que necesitas y escríbenos.'],['02','Déjanos tu ropa','Coordinamos la entrega a tu conveniencia.'],['03','Nos encargamos','Lavamos cada prenda con atención.'],['04','Disfruta tu tiempo','Recíbela limpia y lista para usar.']] as [$n,$t,$d])<div class="relative text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-sky-500 text-sm font-bold text-white ring-8 ring-white">{{ $n }}</span><h3 class="mt-6 font-bold text-slate-900">{{ $t }}</h3><p class="mx-auto mt-2 max-w-48 text-sm leading-6 text-slate-500">{{ $d }}</p></div>@endforeach</div></div></section>
 <section id="experiencias" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><x-section-heading eyebrow="Pensado para tu ritmo" title="Una experiencia que se adapta a ti"/><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">@foreach([['No tienes tiempo','Nosotros nos ocupamos de la ropa.'],['Mucha ropa','Soluciones para grandes cantidades.'],['Prendas delicadas','Procesos especiales para cada tejido.'],['Tienes un negocio','Un aliado confiable para tu operación.']] as [$title,$copy])<article class="rounded-3xl bg-sky-50 p-7"><x-icon name="sparkles" class="h-7 w-7 text-sky-500"/><h3 class="mt-12 text-lg font-bold text-slate-900">¿{{ $title }}?</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $copy }}</p></article>@endforeach</div></section>
 <section class="bg-slate-950 py-24 text-white"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center eyebrow="Experiencias reales" title="Lo que dicen nuestros clientes" text="Pequeños detalles que hacen una gran diferencia." class="[&>h2]:text-white [&>p]:text-slate-400"/><div class="mt-14 grid gap-5 md:grid-cols-3">@foreach([['María G.','Excelente servicio. Mi ropa quedó impecable y la atención fue súper amable.','Cliente semanal'],['Carlos R.','Me salvaron con mi edredón. Volvió limpio, suave y con un aroma increíble.','Cliente ocasional'],['Lucía B.','Puntuales, cuidadosos y muy fáciles de contactar. Ya son mi lavandería de confianza.','Cliente mensual']] as [$name,$quote,$type])<figure class="rounded-3xl bg-white/5 p-7 ring-1 ring-white/10"><div class="text-amber-300">★★★★★</div><blockquote class="mt-5 text-lg leading-7 text-slate-100">“{{ $quote }}”</blockquote><figcaption class="mt-7 text-sm"><b>{{ $name }}</b><span class="ml-2 text-slate-400">{{ $type }}</span></figcaption></figure>@endforeach</div><div class="mt-14 border-t border-white/10 pt-10"><p class="text-center text-xs font-bold uppercase tracking-[.25em] text-slate-500">Empresas que confían en nosotros</p><div class="mt-8 flex flex-wrap justify-center gap-x-12 gap-y-5 text-lg font-bold tracking-widest text-slate-500"><span>HOTEL</span><span>RESTAURANTE</span><span>SPA</span><span>OFICINA</span><span>GIMNASIO</span></div></div></div></section>
 <section class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><x-section-heading center eyebrow="Nuestro espacio" title="Cuidado en cada etapa"/><div class="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">@foreach(['photo-1558618666-fcd25c85cd64','photo-1582735689369-4fe89db7114c','photo-1604335399105-a0c585fd81a1','photo-1626806787461-102c1bfaaea1'] as $i=>$photo)<button @click="modal={{ $i }}" class="group overflow-hidden rounded-2xl {{ $i === 0 ? 'row-span-2' : '' }}"><img class="h-full min-h-40 w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" src="https://images.unsplash.com/{{ $photo }}?auto=format&fit=crop&w=700&q=80" alt="Instalaciones y proceso de {{ $business['name'] }}"></button>@endforeach</div></section>
 <section id="precios" class="bg-sky-50 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><x-section-heading center eyebrow="Sin sorpresas" title="Precios claros, servicio excepcional" text="Consultanos según el tipo y la cantidad de prendas para recibir una cotización precisa."/><div class="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Lavado','Secado','Planchado','Lavado + secado'] as $i=>$item)<div class="rounded-2xl bg-white p-6 text-center shadow-sm"><p class="font-bold text-slate-900">{{ $item }}</p><p class="mt-4 text-2xl font-bold text-sky-600">Gs. XX.XXX</p><p class="mt-1 text-xs text-slate-400">Desde · según prenda</p></div>@endforeach</div><div class="mt-10 text-center"><x-button href="#contacto">Consultar precios</x-button></div></div></section>
 <section id="preguntas" class="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><x-section-heading eyebrow="Te ayudamos" title="Preguntas frecuentes" text="Todo lo que necesitás saber, antes de dejarnos el trabajo."/><div class="divide-y divide-slate-200">@foreach([['¿Cuánto demora el servicio?','El tiempo depende del servicio y volumen. Al confirmar tu solicitud te indicamos una fecha de entrega clara.'],['¿Lavan todo tipo de prendas?','Evaluamos la etiqueta y composición de cada prenda para aplicar el tratamiento adecuado.'],['¿Realizan lavado en seco?','Sí, contamos con cuidado especializado para prendas delicadas que requieren este proceso.'],['¿Puedo solicitar retiro y entrega?','Consultanos la disponibilidad para tu zona y coordinaremos la opción más cómoda para ti.'],['¿Cómo puedo pagar?','Te informaremos las opciones de pago disponibles al coordinar tu servicio.']] as $index=>[$q,$a])<div class="py-5"><button @click="activeFaq === {{ $index }} ? activeFaq=null : activeFaq={{ $index }}" class="flex w-full items-center justify-between gap-5 text-left font-bold text-slate-900"><span>{{ $q }}</span><span class="text-xl text-sky-500" x-text="activeFaq === {{ $index }} ? '−' : '+'"></span></button><p x-show="activeFaq === {{ $index }}" x-collapse class="pt-3 pr-8 leading-7 text-slate-500">{{ $a }}</p></div>@endforeach</div></section>
 <section id="contacto" class="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div class="grid overflow-hidden rounded-[2.5rem] bg-sky-500 lg:grid-cols-2"><div class="p-9 text-white sm:p-14"><p class="text-xs font-bold uppercase tracking-[.2em] text-sky-100">Hablemos</p><h2 class="mt-5 font-display text-4xl font-semibold tracking-tight">Tu ropa está en buenas manos.</h2><p class="mt-5 leading-7 text-sky-50">Déjanos el trabajo pesado y disfruta de más tiempo para ti.</p><div class="mt-10 space-y-5 text-sm">@foreach([['pin',$business['address']],['phone',$business['phone']],['mail',$business['email']],['clock',$business['hours'][0].' · '.$business['hours'][1]]] as [$icon,$value])<div class="flex gap-3"><x-icon :name="$icon" class="h-5 w-5 text-sky-100"/><span>{{ $value }}</span></div>@endforeach</div></div><form class="bg-white p-9 sm:p-14" @submit.prevent="alert('¡Gracias! Tu consulta fue enviada correctamente.')"><h3 class="text-2xl font-bold tracking-tight text-slate-900">Solicita tu servicio</h3><div class="mt-7 grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold text-slate-700">Nombre<input required class="mt-2 w-full rounded-xl border-slate-200 px-4 py-3 text-sm focus:border-sky-500 focus:ring-sky-500" placeholder="Tu nombre"></label><label class="text-sm font-semibold text-slate-700">Teléfono<input required type="tel" class="mt-2 w-full rounded-xl border-slate-200 px-4 py-3 text-sm focus:border-sky-500 focus:ring-sky-500" placeholder="Tu teléfono"></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">Servicio<select class="mt-2 w-full rounded-xl border-slate-200 px-4 py-3 text-sm focus:border-sky-500 focus:ring-sky-500"><option>Selecciona un servicio</option><option>Lavado + Secado</option><option>Planchado</option><option>Lavado en seco</option></select></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">Mensaje<textarea class="mt-2 w-full rounded-xl border-slate-200 px-4 py-3 text-sm focus:border-sky-500 focus:ring-sky-500" rows="3" placeholder="Cuéntanos qué necesitas"></textarea></label></div><button class="mt-6 inline-flex w-full items-center justify-center rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-sky-600">Enviar consulta</button><p class="mt-3 text-center text-xs text-slate-400">Te responderemos a la brevedad.</p></form></div></section>
</main>
<footer class="bg-slate-950 text-slate-400"><div class="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><a class="text-xl font-bold text-white">{{ $business['name'] }}<i class="text-sky-400">.</i></a><p class="mt-4 max-w-52 text-sm leading-6">{{ $business['tagline'] }}</p></div><div><h3 class="font-bold text-white">Servicios</h3><ul class="mt-4 space-y-2 text-sm"><li>Lavado</li><li>Secado</li><li>Planchado</li><li>Lavado en seco</li></ul></div><div><h3 class="font-bold text-white">Empresa</h3><ul class="mt-4 space-y-2 text-sm"><li>Nosotros</li><li>Experiencias</li><li>Preguntas frecuentes</li></ul></div><div><h3 class="font-bold text-white">Contacto</h3><p class="mt-4 text-sm">{{ $business['phone'] }}<br>{{ $business['email'] }}</p></div></div><div class="border-t border-white/10 px-5 py-6 text-center text-xs">© 2026 {{ $business['name'] }}. Todos los derechos reservados.</div></footer>
<a href="https://wa.me/{{ $business['whatsapp'] }}?text=Hola%2C%20quisiera%20consultar%20sobre%20los%20servicios%20de%20lavander%C3%ADa." class="fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500 text-white shadow-xl shadow-emerald-600/30 transition hover:scale-110" aria-label="Consultar por WhatsApp"><x-icon name="phone" class="h-6 w-6"/></a>
<div x-show="modal !== null" x-transition class="fixed inset-0 z-[60] grid place-items-center bg-slate-950/90 p-5" @keydown.escape.window="modal=null"><button @click="modal=null" class="absolute right-7 top-6 text-3xl text-white" aria-label="Cerrar">×</button><img :src="['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1500&q=90','https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=1500&q=90','https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=1500&q=90','https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=1500&q=90'][modal]" class="max-h-[85vh] max-w-full rounded-2xl object-contain" alt="Galería ampliada"></div>
</body></html>
