<?php

return [
    'locale_name' => 'English',
    'meta_title' => 'Laundry service for holiday apartments and hotels in Malaga',
    'meta_description' => 'Professional laundry for holiday apartments, hotels and hospitality businesses in Malaga city. Same-day collection and delivery, 7 days a week.',
    'nav' => ['services' => 'Solutions', 'lodgings' => 'For accommodation', 'process' => 'How it works', 'operations' => 'Operations', 'quote' => 'Get a quote', 'pickup' => 'Request collection'],
    'hero' => ['eyebrow' => 'Professional service in Malaga city', 'title' => 'The laundry service for your', 'accent' => 'holiday accommodation.', 'text' => 'Immaculate bed linen and towels for holiday apartments, hotels and hospitality businesses. Same-day collection and delivery, 7 days a week.', 'solutions' => 'View solutions', 'week' => '7 days', 'week_label' => 'a week', 'pickup' => 'Collection included', 'delivery' => 'Same-day delivery'],
    'stats' => [['7 / 7','Weekly service'],['Same day','Collection and delivery'],['Malaga','City centre and city'],['B2B','Professional service']],
    'about' => ['eyebrow' => 'A partner for your accommodation', 'title' => 'We handle the laundry so you can look after your guests.', 'text' => 'We work exclusively with holiday apartments, hotels and hospitality businesses. We understand guest changeovers, tight schedules and the need to always have immaculate textiles available.', 'badge' => 'Operating every day in Malaga city.', 'items' => [['Punctuality','Collection and delivery tailored to your operation.'],['Quality','Clean, fresh and well-presented textiles.'],['Continuity','Service available seven days a week.']], 'whatsapp' => 'Chat on WhatsApp'],
    'services' => ['eyebrow' => 'Hospitality solutions', 'title' => 'Everything you need for every new stay', 'text' => 'We process your accommodation textiles quickly and consistently, ready to welcome the next guest.', 'items' => [['sparkles','Bed linen','Washing, drying and folding sheets, covers, protectors and table linen.'],['heart','Towels and bathrooms','Soft, clean towels ready to replenish every property.'],['clock','Same-day service','Coordinated collection, processing and delivery within the same day.'],['bag','Holiday apartments','A flexible service aligned with arrivals, departures and guest changeovers.'],['shirt','Hotels and hostels','Capacity and consistency to keep your operation running smoothly.'],['check','Restaurants and hospitality','Dining, kitchen and service textiles treated with professional care.']]],
    'process' => ['eyebrow' => 'Simple and coordinated', 'title' => 'Textiles ready within the same day', 'items' => [['01','Message us','Share your location, volume and preferred time on WhatsApp.'],['02','We collect','We visit your accommodation in Malaga city.'],['03','We process','We wash, dry and prepare every item.'],['04','We deliver','Your clean textiles return the same day.']]],
    'operations' => ['eyebrow' => 'Designed for your operation', 'title' => 'We keep pace with tourist occupancy', 'items' => [['Guest changeovers','We coordinate collection between departures and arrivals.'],['Peak occupancy','We adapt the service to each day’s volume.'],['Consistent standard','Every batch arrives clean, folded and ready to use.'],['Direct support','Manage times and requirements easily through WhatsApp.']]],
    'contact' => ['eyebrow' => 'Direct contact', 'title' => 'Your operation cannot wait.', 'text' => 'Arrange collection and delivery for your accommodation textiles in Malaga city through WhatsApp.', 'cta_title' => 'Let’s talk on WhatsApp', 'cta_text' => 'Tell us what type of accommodation you manage, the approximate volume and when you need collection.', 'button' => 'Contact us on WhatsApp', 'response' => 'We will reply as soon as possible.'],
];
