<?php

return [
    'locale_name' => 'Español',
    'meta_title' => 'Lavandería para apartamentos turísticos y hoteles en Málaga',
    'meta_description' => 'Lavandería profesional para apartamentos turísticos, hoteles y hostelería en Málaga capital. Recogida y entrega en el mismo día, los 7 días.',
    'nav' => ['services' => 'Soluciones', 'lodgings' => 'Para alojamientos', 'process' => 'Cómo funciona', 'operations' => 'Operativa', 'quote' => 'Presupuesto', 'pickup' => 'Solicitar recogida'],
    'hero' => ['eyebrow' => 'Servicio profesional en Málaga capital', 'title' => 'La lavandería de tu', 'accent' => 'alojamiento turístico.', 'text' => 'Ropa de cama y baño impecable para apartamentos turísticos, hoteles y negocios de hostelería. Recogemos y entregamos en el mismo día, los 7 días de la semana.', 'solutions' => 'Ver soluciones', 'week' => '7 días', 'week_label' => 'a la semana', 'pickup' => 'Recogida incluida', 'delivery' => 'Entrega el mismo día'],
    'stats' => [['7 / 7','Servicio semanal'],['Mismo día','Recogida y entrega'],['Málaga','Centro y capital'],['B2B','Atención profesional']],
    'about' => ['eyebrow' => 'Un aliado para tu alojamiento', 'title' => 'Nos ocupamos de la colada para que tú cuides de tus huéspedes.', 'text' => 'Trabajamos exclusivamente con apartamentos turísticos, hoteles y negocios de hostelería. Entendemos los cambios de huéspedes, los tiempos ajustados y la importancia de disponer siempre de textiles impecables.', 'badge' => 'Operativos todos los días en Málaga capital.', 'items' => [['Puntualidad','Recogemos y entregamos según tu operativa.'],['Calidad','Textiles limpios, frescos y bien presentados.'],['Continuidad','Servicio disponible los siete días.']], 'whatsapp' => 'Hablar por WhatsApp'],
    'services' => ['eyebrow' => 'Soluciones para hostelería', 'title' => 'Todo lo necesario para cada nueva estancia', 'text' => 'Procesamos los textiles de tu alojamiento con rapidez, consistencia y una presentación preparada para recibir al siguiente huésped.', 'items' => [['sparkles','Ropa de cama','Lavado, secado y doblado de sábanas, fundas, protectores y mantelería.'],['heart','Toallas y baño','Toallas suaves, limpias y listas para reponer en cada alojamiento.'],['clock','Servicio en el mismo día','Recogida, procesamiento y entrega coordinados dentro de la misma jornada.'],['bag','Apartamentos turísticos','Un servicio flexible que acompaña tus entradas, salidas y cambios de huéspedes.'],['shirt','Hoteles y hostales','Capacidad y regularidad para mantener tu operativa sin interrupciones.'],['check','Restauración y hostelería','Textiles de sala, cocina y servicio tratados con cuidado profesional.']]],
    'process' => ['eyebrow' => 'Simple y coordinado', 'title' => 'Textiles listos dentro de la misma jornada', 'items' => [['01','Escríbenos','Indica tu ubicación, volumen y horario por WhatsApp.'],['02','Recogemos','Pasamos por tu alojamiento en Málaga capital.'],['03','Procesamos','Lavamos, secamos y preparamos cada pieza.'],['04','Entregamos','Recibes los textiles limpios en el mismo día.']]],
    'operations' => ['eyebrow' => 'Diseñado para tu operativa', 'title' => 'Respondemos al ritmo de la ocupación turística', 'items' => [['Cambios de huéspedes','Coordinamos la recogida entre salidas y nuevas entradas.'],['Picos de ocupación','Adaptamos el servicio al volumen de cada jornada.'],['Estándar constante','Cada lote se entrega limpio, doblado y listo para usar.'],['Atención directa','Gestiona horarios y necesidades fácilmente por WhatsApp.']]],
    'contact' => ['eyebrow' => 'Contacto directo', 'title' => 'Tu operativa no puede esperar.', 'text' => 'Coordina por WhatsApp la recogida y entrega de los textiles de tu alojamiento en Málaga capital.', 'cta_title' => 'Hablemos por WhatsApp', 'cta_text' => 'Cuéntanos qué tipo de alojamiento gestionas, el volumen aproximado y cuándo necesitas la recogida.', 'button' => 'Contactar por WhatsApp', 'response' => 'Te responderemos lo antes posible.'],
];
