<?php

return [
    'locale_name' => 'Português',
    'meta_title' => 'Lavandaria para apartamentos turísticos e hotéis em Málaga',
    'meta_description' => 'Lavandaria profissional para apartamentos turísticos, hotéis e hotelaria em Málaga. Recolha e entrega no mesmo dia, 7 dias por semana.',
    'nav' => ['services' => 'Soluções', 'lodgings' => 'Para alojamentos', 'process' => 'Como funciona', 'operations' => 'Operação', 'quote' => 'Orçamento', 'pickup' => 'Solicitar recolha'],
    'hero' => ['eyebrow' => 'Serviço profissional em Málaga', 'title' => 'A lavandaria do seu', 'accent' => 'alojamento turístico.', 'text' => 'Roupa de cama e banho impecável para apartamentos turísticos, hotéis e empresas de hotelaria. Recolha e entrega no mesmo dia, 7 dias por semana.', 'solutions' => 'Ver soluções', 'week' => '7 dias', 'week_label' => 'por semana', 'pickup' => 'Recolha incluída', 'delivery' => 'Entrega no mesmo dia'],
    'stats' => [['7 / 7','Serviço semanal'],['Mesmo dia','Recolha e entrega'],['Málaga','Centro e cidade'],['B2B','Atendimento profissional']],
    'about' => ['eyebrow' => 'Um parceiro para o seu alojamento', 'title' => 'Tratamos da lavandaria para que cuide dos seus hóspedes.', 'text' => 'Trabalhamos exclusivamente com apartamentos turísticos, hotéis e empresas de hotelaria. Compreendemos as mudanças de hóspedes, os prazos apertados e a importância de ter sempre têxteis impecáveis.', 'badge' => 'Operacionais todos os dias em Málaga.', 'items' => [['Pontualidade','Recolha e entrega adaptadas à sua operação.'],['Qualidade','Têxteis limpos, frescos e bem apresentados.'],['Continuidade','Serviço disponível sete dias por semana.']], 'whatsapp' => 'Falar pelo WhatsApp'],
    'services' => ['eyebrow' => 'Soluções para hotelaria', 'title' => 'Tudo para cada nova estadia', 'text' => 'Processamos os têxteis do seu alojamento com rapidez e consistência, prontos para receber o próximo hóspede.', 'items' => [['sparkles','Roupa de cama','Lavagem, secagem e dobra de lençóis, capas, protetores e toalhas de mesa.'],['heart','Toalhas e banho','Toalhas macias e limpas, prontas para repor em cada alojamento.'],['clock','Serviço no mesmo dia','Recolha, processamento e entrega coordenados no mesmo dia.'],['bag','Apartamentos turísticos','Serviço flexível para entradas, saídas e mudanças de hóspedes.'],['shirt','Hotéis e hostels','Capacidade e regularidade para manter a operação sem interrupções.'],['check','Restauração e hotelaria','Têxteis de sala, cozinha e serviço tratados profissionalmente.']]],
    'process' => ['eyebrow' => 'Simples e coordenado', 'title' => 'Têxteis prontos no mesmo dia', 'items' => [['01','Escreva-nos','Indique localização, volume e horário pelo WhatsApp.'],['02','Recolhemos','Vamos ao seu alojamento em Málaga.'],['03','Processamos','Lavamos, secamos e preparamos cada peça.'],['04','Entregamos','Receba os têxteis limpos no mesmo dia.']]],
    'operations' => ['eyebrow' => 'Pensado para a sua operação', 'title' => 'Acompanhamos o ritmo da ocupação turística', 'items' => [['Mudanças de hóspedes','Coordenamos a recolha entre saídas e novas entradas.'],['Picos de ocupação','Adaptamos o serviço ao volume de cada dia.'],['Padrão constante','Cada lote chega limpo, dobrado e pronto a usar.'],['Atendimento direto','Organize horários e necessidades pelo WhatsApp.']]],
    'contact' => ['eyebrow' => 'Contacto direto', 'title' => 'A sua operação não pode esperar.', 'text' => 'Coordene pelo WhatsApp a recolha e entrega dos têxteis do seu alojamento em Málaga.', 'cta_title' => 'Fale connosco pelo WhatsApp', 'cta_text' => 'Diga-nos que tipo de alojamento gere, o volume aproximado e quando precisa da recolha.', 'button' => 'Contactar pelo WhatsApp', 'response' => 'Responderemos o mais rapidamente possível.'],
];
